development:
  host: localhost
  port: 5432
  database: lls_dev
  username: postgres
  password: 
  max_connections: 5

production: 
  host: localhost
  port: 5432
  database: lls_prod
  username: lls
  password: llspwd
  max_connections: 10